### ISSUE TITLE
Add new car

### ISSUE THREAD

**Issue by GoldenZero** [GoldenZero/leasingproject#30]
Note found file: http://easylease.jaziil.com/theme/backend/img/arrow-up.png

An invalid form control with name='name_en' is not focusable

**Comment by GoldenZero** [comment]
![image](https://cloud.githubusercontent.com/assets/2990487/3226024/080493b8-f063-11e3-8677-13440adf5d9e.png)

**Comment by GoldenZero** [comment]
![image](https://cloud.githubusercontent.com/assets/2990487/3226025/1aca8eb2-f063-11e3-9e74-b70415d32c26.png)

**Comment by mhddurrah** [comment]
for image upload issue add ( "intervention/image": "2.*" ) to composer.json and make an update. it is due to Image Resize plugin.
