### ISSUE TITLE
Home page issues

### ISSUE THREAD

**Issue by GoldenZero** [GoldenZero/leasingproject#31]
![image](https://cloud.githubusercontent.com/assets/2990487/3280775/84d1be26-f47c-11e3-9aa3-d1253d758c36.png)

**Comment by GoldenZero** [comment]
![image](https://cloud.githubusercontent.com/assets/2990487/3280778/c690e6e8-f47c-11e3-9e62-c837a576c89d.png)

**Comment by GoldenZero** [comment]
![image](https://cloud.githubusercontent.com/assets/2990487/3280780/defcfab4-f47c-11e3-9521-bc854b771be6.png)

**Comment by GoldenZero** [comment]
![image](https://cloud.githubusercontent.com/assets/2990487/3280787/32fbbda8-f47d-11e3-8172-5543f222faf1.png)

**Comment by mhddurrah** [comment]
fixed. but still have issues with anchor scrolling.
